### ISSUE TITLE
Avoid sudo mrt

### ISSUE THREAD

**Issue by chmac** [awatson1978/meteor-cookbook#31]
As a general rule, package management like npm mixed with sudo is bad. This is especially true for something as young and fresh as meteorite.

I noticed a lot of `sudo mrt ...` in the cookbook, would be better to remove the `sudo` and just leave it as `mrt ...`.

**Comment by awatson1978** [comment]
Substantive effort to replace ``sudo mrt` with ``meteor`` as part of the Meteor 1.0 upgrade.  Mostly complete.  Am closing as this has been mostly done and is implemented as part of the new styleguide going forward.
