### ISSUE TITLE
Unresolved Mongo symbol

### ISSUE THREAD

**Issue by dotnetwise** [awatson1978/meteor-cookbook#36]
Webstorm reports unresolved variable or symbol `Mongo`

```js
Players = new Mongo.Collection("players");
              ^^^^^
```

**Comment by awatson1978** [comment]
Please make sure you're using Webstorm 9, which includes Meteor support.  If that doesn't solve the issue, we can reopen the ticket.
https://www.jetbrains.com/webstorm/whatsnew/#meteor
