### ISSUE TITLE
Move to Gollum?

### ISSUE THREAD

**Issue by robmoggach** [awatson1978/meteor-cookbook#53]
Be great to get this rebuilt as a gollum powered wiki with code samples in the repo instead of markdown. Just an idea... ;)

**Comment by awatson1978** [comment]
Hi.  Thanks for the feedback.  Not sure about gollum; but I've begun extracting samples into the StarryNight command line utility, and either including the code samples directly in the cookbook or linking via gitmodules.  

As an fyi, I've been changing the focus of the Cookbook from being a generalized Meteor learning resource towards being the whitepaper documentation of the Clinical Meteor Track (a distro I'm putting together).  So, the wiki part is probably not exactly going to happen, as there's already Meteorpedia for that.  

But the reorganization - with code samples in the repo - that's currently happening; and is going to be sort of the new editorial policy going forward.  :)
