### ISSUE TITLE
Convert packages into gitmodules

### ISSUE THREAD

**Issue by awatson1978** [awatson1978/meteor-cookbook#86]

**Comment by awatson1978** [comment]
Completed

**Comment by kaiyes** [comment]
you are on a rolling sprint !!!!

**Comment by awatson1978** [comment]
The end is in sight!  Getting ready to rename, transfer, and seed the clinical-meteor project with 1600 stars and an instruction manual!  ;)

Oh, hey...  want a 3 mo contract at the rates we discussed a few weeks ago?  We're finalizing the next milestones for the New Zealand/Singapore project tomorrow, and I got your studio budgeted for three months.  Ping me!
